learning_rate: 1e-5
epsilon: 1e-8
batch_size: 32
round_num: 50
alpha: 0.7
dataset: "VQA_v1"
num_clients: 5
normalize: "z_score"
eval_folder: "saved_model/z_score_alpha0.7_WeightedVQA_v2FEDUlen_clientall5_vit_bert_all_concat_bert_transformerepcoh_50soft_max"
