learning_rate: 0.00001
epsilon: 0.00000001
batch_size: 32
round_num: 50
alpha: 0.7
dataset: "VQA_v1"
num_clients: 5
normalize: "z_score"
eval_folder: "saved_model/z_score_alpha0.7_WeightedVQA_v2FEDUlen_clientall5_vit_bert_all_concat_bert_transformerepcoh_50soft_max"
